# Generated by Django 3.1.4 on 2021-03-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_revision', models.CharField(choices=[('P', 'Parcial'), ('G', 'Geral')], max_length=10)),
                ('machine_revision_date', models.DateField(max_length=10)),
                ('machine_revision_orin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default=0.0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_status',
            field=models.CharField(choices=[('V', 'Vendido'), ('P', 'Pertence')], max_length=10),
        ),
        migrations.AlterField(
            model_name='oil',
            name='oil_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='money_advance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='total_hours_service_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_operator', models.CharField(max_length=50)),
                ('initial_orin', models.IntegerField(max_length=10)),
                ('final_orin', models.IntegerField(max_length=10)),
                ('service_client', models.CharField(max_length=50)),
                ('money_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hour_valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_value_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machine_service_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelos.machine')),
            ],
        ),
    ]
